/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'resolved' : IDL.Null,
  'submitted' : IDL.Null,
  'in_progress' : IDL.Null,
  'under_review' : IDL.Null,
});
export const Category = IDL.Variant({
  'healthcare' : IDL.Null,
  'public_safety' : IDL.Null,
  'other' : IDL.Null,
  'roads_infrastructure' : IDL.Null,
  'water_supply' : IDL.Null,
  'education' : IDL.Null,
  'electricity' : IDL.Null,
  'sanitation' : IDL.Null,
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const T = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'duration' : IDL.Text,
  'contactInfo' : IDL.Text,
  'adminRemark' : IDL.Opt(IDL.Text),
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'citizenName' : IDL.Text,
  'createdTimestamp' : IDL.Int,
  'category' : Category,
  'updatedTimestamp' : IDL.Int,
  'severity' : Severity,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GrievanceStats = IDL.Record({
  'inProgressCount' : IDL.Nat,
  'totalGrievances' : IDL.Nat,
  'categoryCounts' : IDL.Vec(IDL.Tuple(Category, IDL.Nat)),
  'underReviewCount' : IDL.Nat,
  'resolvedCount' : IDL.Nat,
  'submittedCount' : IDL.Nat,
});
export const GrievanceInput = IDL.Record({
  'duration' : IDL.Text,
  'contactInfo' : IDL.Text,
  'description' : IDL.Text,
  'citizenName' : IDL.Text,
  'category' : Category,
  'severity' : Severity,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRemark' : IDL.Func([IDL.Text, IDL.Text], [T], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllGrievances' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGrievanceById' : IDL.Func([IDL.Text], [T], ['query']),
  'getMyGrievances' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getStats' : IDL.Func([], [GrievanceStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitGrievance' : IDL.Func([GrievanceInput], [IDL.Text, T], []),
  'updateGrievanceStatus' : IDL.Func(
      [IDL.Text, Status, IDL.Opt(IDL.Text)],
      [T],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'resolved' : IDL.Null,
    'submitted' : IDL.Null,
    'in_progress' : IDL.Null,
    'under_review' : IDL.Null,
  });
  const Category = IDL.Variant({
    'healthcare' : IDL.Null,
    'public_safety' : IDL.Null,
    'other' : IDL.Null,
    'roads_infrastructure' : IDL.Null,
    'water_supply' : IDL.Null,
    'education' : IDL.Null,
    'electricity' : IDL.Null,
    'sanitation' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const T = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'duration' : IDL.Text,
    'contactInfo' : IDL.Text,
    'adminRemark' : IDL.Opt(IDL.Text),
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'citizenName' : IDL.Text,
    'createdTimestamp' : IDL.Int,
    'category' : Category,
    'updatedTimestamp' : IDL.Int,
    'severity' : Severity,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GrievanceStats = IDL.Record({
    'inProgressCount' : IDL.Nat,
    'totalGrievances' : IDL.Nat,
    'categoryCounts' : IDL.Vec(IDL.Tuple(Category, IDL.Nat)),
    'underReviewCount' : IDL.Nat,
    'resolvedCount' : IDL.Nat,
    'submittedCount' : IDL.Nat,
  });
  const GrievanceInput = IDL.Record({
    'duration' : IDL.Text,
    'contactInfo' : IDL.Text,
    'description' : IDL.Text,
    'citizenName' : IDL.Text,
    'category' : Category,
    'severity' : Severity,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRemark' : IDL.Func([IDL.Text, IDL.Text], [T], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllGrievances' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGrievanceById' : IDL.Func([IDL.Text], [T], ['query']),
    'getMyGrievances' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getStats' : IDL.Func([], [GrievanceStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitGrievance' : IDL.Func([GrievanceInput], [IDL.Text, T], []),
    'updateGrievanceStatus' : IDL.Func(
        [IDL.Text, Status, IDL.Opt(IDL.Text)],
        [T],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };