/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'healthcare' : null } |
  { 'public_safety' : null } |
  { 'other' : null } |
  { 'roads_infrastructure' : null } |
  { 'water_supply' : null } |
  { 'education' : null } |
  { 'electricity' : null } |
  { 'sanitation' : null };
export interface GrievanceInput {
  'duration' : string,
  'contactInfo' : string,
  'description' : string,
  'citizenName' : string,
  'category' : Category,
  'severity' : Severity,
  'location' : string,
}
export interface GrievanceStats {
  'inProgressCount' : bigint,
  'totalGrievances' : bigint,
  'categoryCounts' : Array<[Category, bigint]>,
  'underReviewCount' : bigint,
  'resolvedCount' : bigint,
  'submittedCount' : bigint,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Status = { 'resolved' : null } |
  { 'submitted' : null } |
  { 'in_progress' : null } |
  { 'under_review' : null };
export interface T {
  'id' : string,
  'status' : Status,
  'duration' : string,
  'contactInfo' : string,
  'adminRemark' : [] | [string],
  'submittedBy' : Principal,
  'description' : string,
  'citizenName' : string,
  'createdTimestamp' : bigint,
  'category' : Category,
  'updatedTimestamp' : bigint,
  'severity' : Severity,
  'department' : string,
  'location' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRemark' : ActorMethod<[string, string], T>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllGrievances' : ActorMethod<[], Array<T>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGrievanceById' : ActorMethod<[string], T>,
  'getMyGrievances' : ActorMethod<[], Array<T>>,
  'getStats' : ActorMethod<[], GrievanceStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitGrievance' : ActorMethod<[GrievanceInput], [string, T]>,
  'updateGrievanceStatus' : ActorMethod<[string, Status, [] | [string]], T>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];