/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface T {
    id: string;
    status: Status;
    duration: string;
    contactInfo: string;
    adminRemark?: string;
    submittedBy: Principal;
    description: string;
    citizenName: string;
    createdTimestamp: bigint;
    category: Category;
    updatedTimestamp: bigint;
    severity: Severity;
    department: string;
    location: string;
}
export interface GrievanceStats {
    inProgressCount: bigint;
    totalGrievances: bigint;
    categoryCounts: Array<[Category, bigint]>;
    underReviewCount: bigint;
    resolvedCount: bigint;
    submittedCount: bigint;
}
export interface GrievanceInput {
    duration: string;
    contactInfo: string;
    description: string;
    citizenName: string;
    category: Category;
    severity: Severity;
    location: string;
}
export interface UserProfile {
    name: string;
}
export enum Category {
    healthcare = "healthcare",
    public_safety = "public_safety",
    other = "other",
    roads_infrastructure = "roads_infrastructure",
    water_supply = "water_supply",
    education = "education",
    electricity = "electricity",
    sanitation = "sanitation"
}
export enum Severity {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Status {
    resolved = "resolved",
    submitted = "submitted",
    in_progress = "in_progress",
    under_review = "under_review"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRemark(id: string, remark: string): Promise<T>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllGrievances(): Promise<Array<T>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGrievanceById(id: string): Promise<T>;
    getMyGrievances(): Promise<Array<T>>;
    getStats(): Promise<GrievanceStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitGrievance(input: GrievanceInput): Promise<[string, T]>;
    updateGrievanceStatus(id: string, newStatus: Status, remark: string | null): Promise<T>;
}
import type { Category as _Category, GrievanceInput as _GrievanceInput, GrievanceStats as _GrievanceStats, Severity as _Severity, Status as _Status, T as _T, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRemark(arg0: string, arg1: string): Promise<T> {
        if (this.processError) {
            try {
                const result = await this.actor.addRemark(arg0, arg1);
                return from_candid_T_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRemark(arg0, arg1);
            return from_candid_T_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllGrievances(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGrievances();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGrievances();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrievanceById(arg0: string): Promise<T> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrievanceById(arg0);
                return from_candid_T_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrievanceById(arg0);
            return from_candid_T_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGrievances(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGrievances();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGrievances();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<GrievanceStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return from_candid_GrievanceStats_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return from_candid_GrievanceStats_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitGrievance(arg0: GrievanceInput): Promise<[string, T]> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGrievance(to_candid_GrievanceInput_n20(this._uploadFile, this._downloadFile, arg0));
                return [
                    result[0],
                    from_candid_T_n1(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGrievance(to_candid_GrievanceInput_n20(this._uploadFile, this._downloadFile, arg0));
            return [
                result[0],
                from_candid_T_n1(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async updateGrievanceStatus(arg0: string, arg1: Status, arg2: string | null): Promise<T> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGrievanceStatus(arg0, to_candid_Status_n26(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
                return from_candid_T_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGrievanceStatus(arg0, to_candid_Status_n26(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
            return from_candid_T_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_GrievanceStats_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GrievanceStats): GrievanceStats {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_T_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inProgressCount: bigint;
    totalGrievances: bigint;
    categoryCounts: Array<[_Category, bigint]>;
    underReviewCount: bigint;
    resolvedCount: bigint;
    submittedCount: bigint;
}): {
    inProgressCount: bigint;
    totalGrievances: bigint;
    categoryCounts: Array<[Category, bigint]>;
    underReviewCount: bigint;
    resolvedCount: bigint;
    submittedCount: bigint;
} {
    return {
        inProgressCount: value.inProgressCount,
        totalGrievances: value.totalGrievances,
        categoryCounts: from_candid_vec_n18(_uploadFile, _downloadFile, value.categoryCounts),
        underReviewCount: value.underReviewCount,
        resolvedCount: value.resolvedCount,
        submittedCount: value.submittedCount
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    duration: string;
    contactInfo: string;
    adminRemark: [] | [string];
    submittedBy: Principal;
    description: string;
    citizenName: string;
    createdTimestamp: bigint;
    category: _Category;
    updatedTimestamp: bigint;
    severity: _Severity;
    department: string;
    location: string;
}): {
    id: string;
    status: Status;
    duration: string;
    contactInfo: string;
    adminRemark?: string;
    submittedBy: Principal;
    description: string;
    citizenName: string;
    createdTimestamp: bigint;
    category: Category;
    updatedTimestamp: bigint;
    severity: Severity;
    department: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        duration: value.duration,
        contactInfo: value.contactInfo,
        adminRemark: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.adminRemark)),
        submittedBy: value.submittedBy,
        description: value.description,
        citizenName: value.citizenName,
        createdTimestamp: value.createdTimestamp,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category),
        updatedTimestamp: value.updatedTimestamp,
        severity: from_candid_Severity_n8(_uploadFile, _downloadFile, value.severity),
        department: value.department,
        location: value.location
    };
}
function from_candid_tuple_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Category, bigint]): [Category, bigint] {
    return [
        from_candid_Category_n6(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    submitted: null;
} | {
    in_progress: null;
} | {
    under_review: null;
}): Status {
    return "resolved" in value ? Status.resolved : "submitted" in value ? Status.submitted : "in_progress" in value ? Status.in_progress : "under_review" in value ? Status.under_review : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthcare: null;
} | {
    public_safety: null;
} | {
    other: null;
} | {
    roads_infrastructure: null;
} | {
    water_supply: null;
} | {
    education: null;
} | {
    electricity: null;
} | {
    sanitation: null;
}): Category {
    return "healthcare" in value ? Category.healthcare : "public_safety" in value ? Category.public_safety : "other" in value ? Category.other : "roads_infrastructure" in value ? Category.roads_infrastructure : "water_supply" in value ? Category.water_supply : "education" in value ? Category.education : "electricity" in value ? Category.electricity : "sanitation" in value ? Category.sanitation : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "medium" in value ? Severity.medium : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Category, bigint]>): Array<[Category, bigint]> {
    return value.map((x)=>from_candid_tuple_n19(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_GrievanceInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GrievanceInput): _GrievanceInput {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: string;
    contactInfo: string;
    description: string;
    citizenName: string;
    category: Category;
    severity: Severity;
    location: string;
}): {
    duration: string;
    contactInfo: string;
    description: string;
    citizenName: string;
    category: _Category;
    severity: _Severity;
    location: string;
} {
    return {
        duration: value.duration,
        contactInfo: value.contactInfo,
        description: value.description,
        citizenName: value.citizenName,
        category: to_candid_Category_n22(_uploadFile, _downloadFile, value.category),
        severity: to_candid_Severity_n24(_uploadFile, _downloadFile, value.severity),
        location: value.location
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    healthcare: null;
} | {
    public_safety: null;
} | {
    other: null;
} | {
    roads_infrastructure: null;
} | {
    water_supply: null;
} | {
    education: null;
} | {
    electricity: null;
} | {
    sanitation: null;
} {
    return value == Category.healthcare ? {
        healthcare: null
    } : value == Category.public_safety ? {
        public_safety: null
    } : value == Category.other ? {
        other: null
    } : value == Category.roads_infrastructure ? {
        roads_infrastructure: null
    } : value == Category.water_supply ? {
        water_supply: null
    } : value == Category.education ? {
        education: null
    } : value == Category.electricity ? {
        electricity: null
    } : value == Category.sanitation ? {
        sanitation: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Severity.low ? {
        low: null
    } : value == Severity.high ? {
        high: null
    } : value == Severity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    resolved: null;
} | {
    submitted: null;
} | {
    in_progress: null;
} | {
    under_review: null;
} {
    return value == Status.resolved ? {
        resolved: null
    } : value == Status.submitted ? {
        submitted: null
    } : value == Status.in_progress ? {
        in_progress: null
    } : value == Status.under_review ? {
        under_review: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
